### PR TITLE
Bug fix/validation for parameters

### PR DESCRIPTION
**Pull request by Kaybangz**
# Which issue are you addressing?

#51
## How have you addressed the issue?

1. Removed `Barrier()` from `Parallel.Ordered` method
2. Moved the body of the `If` statements in `ValidateParameters()` method to a new indented line
3. In `Exception.cs`, added a space before the `:` tokens
4. Used `ValidateParameters()` only at the top of the internal `For` handler
5. Removed the spaces on line 250 in `Parallel.cs`
6. Added a descriptive message to the custom `NotInForException`

### CODE REVIEW

**Review by computablee — CHANGES_REQUESTED** [review]
The checks are failing, the code doesn't compile. Please fix the compile issues and we'll go from there.

**Comment by Kaybangz** [comment]
Hey @computablee, do you seem to have any idea why compilation is failing and how I can go about fixing?

I would also like to know how to run tests on my end, to ensure that everything works before making a PR.

I apologize for the inconvenience

**Comment by computablee** [comment]
It looks like you have mismatched names in your added function (e.g., you accept `chunkSize` as a parameter, but later reference a `chunk_size` variable... this is the case with numerous variables).

If you have the `dotnet` CLI installed, you can navigate to the `DotMP-Tests/` directory and run `dotnet test --verbose` in your command line—this will ensure not only that everything compiles, but that some 40-ish other integration tests pass.

I also recommend reading the new `CONTRIBUTING.md` in the main branch I updated tonight—it outlines several important things about opening a PR, such as things that are grounds for immediate rejection, code formatting and styling, and testing. These will be enforced moving forward.

**Comment by Kaybangz** [comment]
Alright, noted.

**Comment by Kaybangz** [comment]
I keep getting this error `Failed to read environment variables [DOTNET_STARTUP_HOOK], HRESULT: 0X800700CB` when I try to run the `dotnet test --verbose`, `dotnet format` or `dotnet build`.

Can I push my changes without testing, since I have made all necessary changes or is there any other suggestion you have for rectifying this problem?

Build_error_1
Build_error_2
Build_error_3

**Comment by computablee** [comment]
Hey @Kaybangz, sorry for the late response. I have recently adopted a cat and have not even had time to open GitHub.

I would recommend asking around in the [C# Discord](https://discord.gg/csharp) to see if they can fix your problem. Unfortunately, I cannot help diagnose issues with the dotnet CLI—I merely maintain a .NET project which uses it.

**Comment by Kaybangz** [comment]
Congrats on adopting a cat😊 

I'll be sure to check out the Discord group

**Comment by computablee** [comment]
In order to expedite this issue to get the next major release out, I am closing this PR and self-assigning #51.

**Pull request closed without merging**
