### PR TITLE
Fix DotMP.Parallel.Single

### LINKED ISSUE #47: `DotMP.Parallel.Single` should act as a barrier
Currently, the `DotMP.Parallel.Single` construct behaves a bit differently than `#pragma omp single`.

1. `DotMP.Parallel.Single` should act as an implicit barrier, but it does not.
2. `DotMP.Parallel.Single` should not be permitted to be used inside of a work sharing region like `Parallel.For` or `Parallel.ForReduction`.

This shouldn't be too difficult of a fix-- `Single` needs to check if the `in_for` flag is set inside of the `WorkShare` singleton, and if it is, it should throw an exception. Additionally, and this is perhaps the easiest aspect to this PR... just add a `Barrier()` call to the end of the `Single()` method.

Make sure documentation is updated as well to reflect the changes!

### PR DESCRIPTION
**Pull request by blouflashdb**
Closes #47

### CODE REVIEW

**Comment by computablee** [comment]
Looking nice, a couple small things before I merge.

1. Recently (today) I went through and added comments to all of the individual exception constructors (see the `main` branch for how this is done in `Exceptions.cs`). Feel free to copy+paste the comments there and reuse them.
2. Along with the commit that addressed the exception comments, I changed all of the references to `<T>` in XML comments to `&lt;T&gt;`. Please change that on line 54 of `Exceptions.cs`.
3. Please include whitespace after the `if` keyword on line 658 of `Parallel.cs`. I need to add a formatter to the CI pipeline, that's on me. I'll open an issue on that right now.
4. Since this is not being pulled into `main`, can you run the tester (`make test` in the root of the repo) and let me know if everything passes?

Nothing you did wrong, it's just that 1 and 2 are to due with how XML documentation changed today due to now being included in the packing process (and `dotnet pack` was dumping out about 200 warnings I went through and tidied up). 3 is just because of a missing code formatter in the CI pipeline, that shouldn't be an issue.

**Comment by blouflashdb** [comment]
Sure.

**Comment by blouflashdb** [comment]
The Single_works is failing because the in_for_pv field is null. I am not sure if this is a problem with the test setup or if this could even be a bug at runtime. Can you take a look?

**Comment by blouflashdb** [comment]
I believe a null check in get_in_for_pv is required like this:

`internal bool in_for
        {
            get
            {
                if (in_for_pv == null) {
                    return false;
                }

                return in_for_pv[Parallel.GetThreadNum()];
            }
            set
            {
                in_for_pv[Parallel.GetThreadNum()] = value;
            }
        }`

**Comment by computablee** [comment]
I agree, please go ahead and make that change and let me know if everything passes.

**Comment by blouflashdb** [comment]
Tests are passing.

**Pull request merged**
